spring:
  application:
    name: wms
  profiles:
    active: dev
server:
  servlet:
    context-path: /wms/api
  tomcat:
    connection-timeout: 20s
mybatis-plus:
  #指向了项目的src/main/resources/mybatis目录 查找所有.xml文件作为映射器文件
  mapper-locations: classpath:mybatis/*.xml
  # 自动扫描这个包及其子包中的所有类，并为它们注册类型别名。这使得在SQL映射文件中引用实体类时可以使用简短的名称而不是全限定名
  type-aliases-package: com.mortal.wms
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
knife4j:
  enable: true
  basic:
    enable: true
    username: root
    password: srgwx7yin!
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  # 过期时间，时间戳（毫秒）（5*60*1000）
  expiresSecond: 604800000